"""`tabella init` — bootstrap the local validation sandbox.

Writes a docker-compose stack (OpenMetadata + its MySQL/OpenSearch
dependencies, Postgres with pgvector, MinIO) into ./tabella-sandbox/ and
starts it, so the full pipeline — register -> OM -> vectorize -> serve — can
run end to end on one machine.

Image tags are pinned via the generated .env file; they track the OM 1.12.x
line our catalog backend targets and get final verification during the live
validation batch.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

COMPOSE_YAML = """\
# Tabella local sandbox — generated by `tabella init`.
# OpenMetadata (+ MySQL + OpenSearch), Postgres w/ pgvector, MinIO.
services:
  om-mysql:
    image: mysql:8.3
    command: --sort_buffer_size=10M
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: openmetadata_user
      MYSQL_PASSWORD: openmetadata_password
      MYSQL_DATABASE: openmetadata_db
    healthcheck:
      test: >-
        mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --silent
        --execute "use openmetadata_db"
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - om-mysql-data:/var/lib/mysql

  om-opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - om-search-data:/usr/share/opensearch/data

  om-migrate:
    image: openmetadata/server:${OM_VERSION}
    command: ./bootstrap/openmetadata-ops.sh migrate
    environment: &om-env
      DB_HOST: om-mysql
      DB_PORT: 3306
      DB_USER: openmetadata_user
      DB_USER_PASSWORD: openmetadata_password
      OM_DATABASE: openmetadata_db
      ELASTICSEARCH_HOST: om-opensearch
      ELASTICSEARCH_PORT: 9200
      SEARCH_TYPE: opensearch
    depends_on:
      om-mysql:
        condition: service_healthy
      om-opensearch:
        condition: service_started

  openmetadata:
    image: openmetadata/server:${OM_VERSION}
    environment: *om-env
    ports:
      - "8585:8585"
    depends_on:
      om-migrate:
        condition: service_completed_successfully

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: tabella
      POSTGRES_PASSWORD: tabella
      POSTGRES_DB: tabella
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: tabella
      MINIO_ROOT_PASSWORD: tabella123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  om-mysql-data:
  om-search-data:
  pg-data:
  minio-data:
"""

ENV_FILE = """\
# Pinned during the live validation batch; tracks the OM 1.12.x line.
OM_VERSION=1.12.2
"""

NEXT_STEPS = """\
Sandbox starting. Endpoints once healthy (OpenMetadata takes a few minutes
on first boot):

  OpenMetadata   http://localhost:8585   (default login: admin@open-metadata.org / admin)
  Postgres       postgres://tabella:tabella@localhost:5433/tabella   (pgvector enabled)
  MinIO          http://localhost:9001   (tabella / tabella123)

Wire Tabella to it:

  export TABELLA_OM_HOST=http://localhost:8585
  export TABELLA_OM_TOKEN=<bot token from OM Settings -> Bots>
  export TABELLA_VECTOR_BACKEND=pgvector
  export TABELLA_VECTOR_PG_URI=postgres://tabella:tabella@localhost:5433/tabella

  tabella register examples/quickstart/customers.yaml --backend openmetadata
  tabella vectorize catalog/

Manage the stack from ./tabella-sandbox:
  docker compose ps | logs -f openmetadata | down [-v]
"""


def init_sandbox(directory: str | Path = "tabella-sandbox", *, start: bool = True) -> int:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    (target / "docker-compose.yml").write_text(COMPOSE_YAML)
    (target / ".env").write_text(ENV_FILE)
    print(f"wrote {target}/docker-compose.yml and {target}/.env")

    if not start:
        print(f"start it with: docker compose --project-directory {target} up -d")
        return 0
    if shutil.which("docker") is None:
        print("docker not found — install Docker, then run:", file=sys.stderr)
        print(f"  docker compose --project-directory {target} up -d", file=sys.stderr)
        return 1
    completed = subprocess.run(  # noqa: S603
        ["docker", "compose", "--project-directory", str(target), "up", "-d"],
        check=False,
    )
    if completed.returncode != 0:
        return completed.returncode
    print(NEXT_STEPS)
    return 0
